apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: order-service
  annotations:
    github.com/project-slug: sergejsvisockis/order-service
spec:
  type: other
  lifecycle: unknown
  owner: sergejs
