version: '3.5'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    command:
      [ "postgres", "-c", "wal_level=logical" ]
    volumes:
      - "vol_postgres:/var/lib/postgresql/data"
    networks:
      - order_manager

  order-service:
    build:
      context: .
    depends_on:
      - db
    ports:
      - '8080:8080'
    networks:
      - order_manager

volumes:
  vol_postgres:

networks:
  order_manager:
    driver: bridge
