version: '3.5'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    command:
      [ "postgres", "-c", "wal_level=logical" ]
    volumes:
      - "vol_postgres:/var/lib/postgresql/data"
    networks:
      - order_manager

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - order-service
    networks:
      - order_manager

  order-service:
    build:
      context: .
    hostname: order-service01
    environment:
      server.port: 8082
    depends_on:
      - db
    expose:
      - '8081'
    networks:
      - order_manager

volumes:
  vol_postgres:

networks:
  order_manager:
    driver: bridge
