spring:
  liquibase:
    change-log: classpath:db/db.changelog-persistence.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 60_000
      idle-timeout: 30_000
      max-lifetime: 3_000_000
      maximum-pool-size: 500
  jpa:
    hibernate:
      ddl-auto: none

springdoc:
  swagger-ui:
    enabled: true
